# Generated by Django 5.1.1 on 2024-09-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_proveedor', models.CharField(max_length=30)),
                ('nombre_proveedor', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'proveedor',
            },
        ),
    ]
