# Generated by Django 5.1.1 on 2024-09-16 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bateria', '0001_initial'),
        ('bomba', '0001_initial'),
        ('cisterna', '0001_initial'),
        ('copa', '0001_initial'),
        ('estado', '0001_initial'),
        ('pozo', '0001_initial'),
        ('punto_interno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Punto_de_control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_punto_de_control', models.CharField(max_length=250)),
                ('estado_retrasos', models.BooleanField(default=False)),
                ('bateria', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='punto_control', to='bateria.bateria')),
                ('bomba', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='punto_control', to='bomba.bomba')),
                ('cisterna', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='punto_control', to='cisterna.cisterna')),
                ('copa', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='punto_control', to='copa.copa')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punto_control', to='estado.estado')),
                ('pozo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='punto_control', to='pozo.pozo')),
                ('punto_interno', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='punto_control', to='punto_interno.punto_interno')),
            ],
            options={
                'db_table': 'punto_control',
            },
        ),
    ]
