# Generated by Django 5.1.1 on 2024-09-16 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bomba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_bomba', models.CharField(max_length=150)),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bomba', to='estado.estado')),
            ],
            options={
                'db_table': 'bomba',
            },
        ),
        migrations.CreateModel(
            name='Bomba_usos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_uso', models.DateField()),
                ('horas_de_uso', models.IntegerField()),
                ('bomba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bomba', to='bomba.bomba')),
            ],
            options={
                'db_table': 'bomba_usos',
            },
        ),
    ]
