# Generated by Django 5.1.1 on 2024-12-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bomba', '0003_bomba_usos_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomba',
            name='latitud',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='bomba',
            name='longitud',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
