# Generated by Django 5.1.1 on 2024-12-02 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analisis', '__first__'),
        ('proveedor', '0001_initial'),
        ('punto_control', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprobado', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField()),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisis.analisis')),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proveedor.proveedor')),
                ('punto_de_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punto_control.punto_de_control')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'control',
            },
        ),
        migrations.CreateModel(
            name='Control_fisico_quimico',
            fields=[
                ('control_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='control.control')),
                ('OLO', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('PH', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('CON', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('STO', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('DUR', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('MAG', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('SOD', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('NIT', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('SUL', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ALC', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('CLO', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('FLU', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ARS', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            bases=('control.control',),
        ),
    ]
