# Generated by Django 5.1.1 on 2024-12-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametro_control_fisico_quimicop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='control_fisico_quimico',
            name='ALC',
        ),
        migrations.RemoveField(
            model_name='control_fisico_quimico',
            name='ARS',
        ),
        migrations.RemoveField(
            model_name='control_fisico_quimico',
            name='CLO',
        ),
        migrations.RemoveField(
            model_name='control_fisico_quimico',
            name='CON',
        ),
        migrations.RemoveField(
            model_name='control_fisico_quimico',
            name='DUR',
        ),
        migrations.RemoveField(
            model_name='control_fisico_quimico',
            name='FLU',
        ),
        migrations.RemoveField(
            model_name='control_fisico_quimico',
            name='MAG',
        ),
        migrations.RemoveField(
            model_name='control_fisico_quimico',
            name='NIT',
        ),
        migrations.RemoveField(
            model_name='control_fisico_quimico',
            name='OLO',
        ),
        migrations.RemoveField(
            model_name='control_fisico_quimico',
            name='PH',
        ),
        migrations.RemoveField(
            model_name='control_fisico_quimico',
            name='SOD',
        ),
        migrations.RemoveField(
            model_name='control_fisico_quimico',
            name='STO',
        ),
        migrations.RemoveField(
            model_name='control_fisico_quimico',
            name='SUL',
        ),
    ]
