# Generated by Django 5.1.1 on 2024-12-02 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_parametro_control_fisico_quimicop_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Control_fisico_quimico',
        ),
    ]
