# Generated by Django 5.1.1 on 2024-12-02 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_delete_control_fisico_quimico'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parametro_control_fisico_quimicop',
        ),
    ]
