# Generated by Django 5.1.1 on 2024-12-02 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '__first__'),
        ('control', '0004_delete_parametro_control_fisico_quimicop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_control', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Valores_control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=50)),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisis.analisis')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.control')),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisis.parametro')),
                ('tipo_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.tipo_control')),
            ],
        ),
    ]
