# Generated by Django 5.1.1 on 2024-12-02 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_tipo_control_valores_control'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='valores_control',
            table='valores_control',
        ),
    ]
