# Generated by Django 5.1.1 on 2024-12-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_alter_valores_control_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='fecha',
            field=models.DateField(),
        ),
    ]
