# Generated by Django 5.1.1 on 2024-12-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0008_control_tipo_control'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='control',
            name='tipo_control',
        ),
    ]
