# Generated by Django 5.1.1 on 2024-12-12 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0009_remove_control_tipo_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='tipo_control',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='control.tipo_control'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='valores_control',
            name='valor',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
