# Generated by Django 5.1.1 on 2024-12-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0010_control_tipo_control_alter_valores_control_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valores_control',
            name='valor',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
