# Generated by Django 5.1.4 on 2024-12-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0011_alter_valores_control_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='hora',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
