# Generated by Django 5.1.4 on 2024-12-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0012_control_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='valores_control',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='valores_control',
            name='hora',
            field=models.TimeField(null=True),
        ),
    ]
