# Generated by Django 5.1.4 on 2024-12-23 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pozo', '0003_caudal_pozo_caudal'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='caudal',
            table='Caudal',
        ),
    ]
