# Generated by Django 5.1.4 on 2024-12-23 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pozo', '0005_alter_caudal_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='pozo',
            name='caudal_total',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pozos', to='pozo.caudal'),
        ),
    ]
