# Generated by Django 5.1.4 on 2024-12-23 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bateria', '0002_bateria_caudal_total'),
        ('pozo', '0006_pozo_caudal_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pozo',
            name='bateria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pozos', to='bateria.bateria'),
        ),
    ]
