# Generated by Django 5.1.1 on 2024-09-16 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_perfil_usuario_usuario_alias_usuario_apellido_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
    ]
