# Generated by Django 5.1.1 on 2024-09-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_usuario_options_alter_usuario_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='alias',
            field=models.CharField(default=None, max_length=50, null=True, unique=True),
        ),
    ]
