# Generated by Django 5.1.1 on 2024-11-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_delete_permisos_perfil_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='alias',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
    ]
