# Generated by Django 5.1.1 on 2024-11-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_alter_usuario_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='alias',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
