# Generated by Django 5.1.1 on 2024-09-16 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('punto_control', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'estado_incidente',
            },
        ),
        migrations.CreateModel(
            name='Gravedad_incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'gravedad_incidente',
            },
        ),
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_operacion', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'operacion',
            },
        ),
        migrations.CreateModel(
            name='Tipo_incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_tipo_incidente', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'tipo_incidente',
            },
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('fecha_incidente', models.DateField()),
                ('fecha_de_registro', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('estado_incidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidente.estado_incidente')),
                ('gravedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidente.gravedad_incidente')),
                ('punto_de_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punto_control.punto_de_control')),
                ('usuario', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'incidente',
            },
        ),
        migrations.CreateModel(
            name='Incidente_operacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('incidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidente.incidente')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidente.operacion')),
            ],
            options={
                'db_table': 'incidente_operacion',
            },
        ),
    ]
