# Generated by Django 5.1.1 on 2024-09-17 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidente',
            name='estado_incidente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidente.operacion'),
        ),
        migrations.DeleteModel(
            name='Estado_incidente',
        ),
    ]
