# Generated by Django 5.1.1 on 2024-09-17 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidente', '0002_alter_incidente_estado_incidente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidente',
            name='tipo_incidente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='incidente.tipo_incidente'),
            preserve_default=False,
        ),
    ]
