# Generated by Django 5.1.1 on 2024-10-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidente', '0004_alter_incidente_estado_incidente'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_incidente',
            name='inhabilitar_elemento',
            field=models.BooleanField(default=False),
        ),
    ]
