# Generated by Django 5.1.1 on 2024-10-29 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidente', '0006_remove_incidente_punto_de_control_incidente_bateria_and_more'),
        ('tipo_elemento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidente',
            name='bateria',
        ),
        migrations.RemoveField(
            model_name='incidente',
            name='bomba',
        ),
        migrations.RemoveField(
            model_name='incidente',
            name='cisterna',
        ),
        migrations.RemoveField(
            model_name='incidente',
            name='copa',
        ),
        migrations.RemoveField(
            model_name='incidente',
            name='pozo',
        ),
        migrations.RemoveField(
            model_name='incidente',
            name='punto_interno',
        ),
        migrations.AddField(
            model_name='incidente',
            name='tipo_elemento',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tipo_elemento.tipo_elemento'),
            preserve_default=False,
        ),
    ]
