# Generated by Django 5.1.1 on 2024-10-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidente', '0007_remove_incidente_bateria_remove_incidente_bomba_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidente',
            name='elemento',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
