# Generated by Django 5.1.1 on 2024-10-29 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bateria', '0001_initial'),
        ('bomba', '0002_bomba_tipo_elemento'),
        ('cisterna', '0004_alter_cisterna_tipo_elemento'),
        ('copa', '0002_copa_tipo_elemento'),
        ('incidente', '0008_incidente_elemento'),
        ('pozo', '0002_pozo_tipo_elemento'),
        ('punto_interno', '0002_punto_interno_tipo_elemento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidente',
            name='elemento',
        ),
        migrations.AddField(
            model_name='incidente',
            name='bateria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bateria.bateria'),
        ),
        migrations.AddField(
            model_name='incidente',
            name='bomba',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bomba.bomba'),
        ),
        migrations.AddField(
            model_name='incidente',
            name='cisterna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cisterna.cisterna'),
        ),
        migrations.AddField(
            model_name='incidente',
            name='copa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='copa.copa'),
        ),
        migrations.AddField(
            model_name='incidente',
            name='pozo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pozo.pozo'),
        ),
        migrations.AddField(
            model_name='incidente',
            name='punto_interno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='punto_interno.punto_interno'),
        ),
    ]
