# Generated by Django 5.1.1 on 2024-10-29 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('incidente', '0009_remove_incidente_elemento_incidente_bateria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidente',
            name='bateria',
        ),
        migrations.RemoveField(
            model_name='incidente',
            name='bomba',
        ),
        migrations.RemoveField(
            model_name='incidente',
            name='cisterna',
        ),
        migrations.RemoveField(
            model_name='incidente',
            name='copa',
        ),
        migrations.RemoveField(
            model_name='incidente',
            name='pozo',
        ),
        migrations.RemoveField(
            model_name='incidente',
            name='punto_interno',
        ),
        migrations.AddField(
            model_name='incidente',
            name='content_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidente',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
