# Generated by Django 5.1.1 on 2024-10-29 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidente', '0010_remove_incidente_bateria_remove_incidente_bomba_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidente',
            old_name='object_id',
            new_name='elemento_id',
        ),
    ]
