# Generated by Django 5.1.1 on 2024-10-29 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('incidente', '0011_rename_object_id_incidente_elemento_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidente',
            name='content_type',
        ),
        migrations.AlterField(
            model_name='incidente',
            name='tipo_elemento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
