# Generated by Django 5.1.1 on 2024-10-29 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidente', '0012_remove_incidente_content_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidente',
            old_name='tipo_elemento',
            new_name='content_type',
        ),
        migrations.RenameField(
            model_name='incidente',
            old_name='elemento_id',
            new_name='object_id',
        ),
    ]
