# Generated by Django 5.1.1 on 2024-10-29 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidente', '0013_rename_tipo_elemento_incidente_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidente',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='incidente',
            name='object_id',
        ),
        migrations.AlterModelTable(
            name='incidente',
            table=None,
        ),
    ]
