# Generated by Django 5.1.1 on 2024-10-29 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidente', '0015_incidente_content_type_incidente_object_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidente',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='incidente',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='incidente',
            name='tipo_elemento',
        ),
        migrations.AlterModelTable(
            name='incidente',
            table='incidente',
        ),
    ]
