# Generated by Django 5.1.1 on 2024-10-29 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidente', '0017_incidente_content_type_incidente_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidente',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='incidente',
            name='object_id',
        ),
    ]
