# Generated by Django 5.1.1 on 2024-11-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidente', '0025_alter_incidente_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidente',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
