# Generated by Django 5.1.1 on 2024-11-06 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidente', '0027_alter_incidente_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidente',
            name='estado_incidente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidente.operacion'),
        ),
    ]
