# Generated by Django 5.1.1 on 2024-11-11 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidente', '0028_alter_incidente_estado_incidente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidente',
            name='punto_de_control',
        ),
    ]
