# Generated by Django 5.1.1 on 2024-11-13 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidente', '0029_remove_incidente_punto_de_control'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidente',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='estado_incidente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='incidente.operacion'),
        ),
    ]
