# Generated by Django 5.1.1 on 2024-11-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidente', '0030_alter_incidente_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidente',
            name='descripcion',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
