# Generated by Django 5.1.1 on 2024-11-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidente', '0032_alter_incidente_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidente_operacion',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
