# Generated by Django 5.1.1 on 2024-12-02 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipo_elemento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametro_codigo', models.CharField(max_length=50)),
                ('nombre_parametro', models.CharField(max_length=200)),
                ('texto', models.BooleanField(default=False)),
                ('numero', models.BooleanField(default=False)),
                ('decimales', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'parametro',
            },
        ),
        migrations.CreateModel(
            name='Periodicidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodicidad_codigo', models.CharField(max_length=50)),
                ('periodicidad_nombre', models.CharField(max_length=250)),
                ('numero_dias', models.IntegerField()),
                ('retraso_dias', models.IntegerField()),
                ('muy_retrasado_dias', models.IntegerField()),
            ],
            options={
                'db_table': 'periodicidad',
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nombre_unidad', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'unidad',
            },
        ),
        migrations.CreateModel(
            name='Intervalo_referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muy_bajo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('bajo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('alto', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('muy_alto', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('muy_bajo_regex', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('bajo_regex', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('alto_regex', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('muy_alto_regex', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('tipo_elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipo_elemento.tipo_elemento')),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisis.parametro')),
            ],
            options={
                'db_table': 'intervalo_referencia',
            },
        ),
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('parametros', models.ManyToManyField(related_name='analisis_parametros', to='analisis.parametro')),
            ],
            options={
                'db_table': 'analisis',
            },
        ),
        migrations.CreateModel(
            name='Periodo_analisis_elemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisis.analisis')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisis.periodicidad')),
                ('tipo_elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipo_elemento.tipo_elemento')),
            ],
            options={
                'db_table': 'periodo_analisis_elemento',
            },
        ),
        migrations.AddField(
            model_name='parametro',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisis.unidad'),
        ),
    ]
