# Generated by Django 5.1.1 on 2024-12-02 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0002_borrar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Borrar',
        ),
    ]
