# Generated by Django 5.1.1 on 2024-12-02 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0003_delete_borrar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Intervalo_referencia',
        ),
    ]
