# Generated by Django 5.1.1 on 2024-12-02 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0004_delete_intervalo_referencia'),
        ('tipo_elemento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervalo_referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muy_bajo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('bajo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('alto', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('muy_alto', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('muy_bajo_regex', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('bajo_regex', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('alto_regex', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('muy_alto_regex', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisis.parametro')),
                ('tipo_elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipo_elemento.tipo_elemento')),
            ],
            options={
                'db_table': 'intervalo_referencia',
            },
        ),
    ]
