# Generated by Django 5.1.1 on 2024-09-16 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estado', '0001_initial'),
        ('localidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cisterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cisterna', models.CharField(max_length=200)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cisterna', to='estado.estado')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cisterna', to='localidad.localidad')),
            ],
            options={
                'db_table': 'cisterna',
            },
        ),
    ]
