# Generated by Django 5.1.1 on 2024-09-16 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipo_elemento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_bateria', models.CharField(max_length=250)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('tipo_elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bateria', to='tipo_elemento.tipo_elemento')),
            ],
            options={
                'db_table': 'bateria',
            },
        ),
    ]
